name: agried
description: AgriEd.

publish_to: "none"
version: 1.0.3+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^3.0.0
  url_launcher: ^6.0.3
  shimmer: ^3.0.0
  metadata_fetch: ^0.4.1
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/flutter_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/dummies/
    - assets/dummies/productivity/
    - assets/images/home/
    - assets/images/resources/
    - assets/images/modules/a/
    - assets/images/modules/b/
    - assets/images/modules/c/
    - assets/images/modules/d/
    - assets/images/reporting/
