name: agried
description: AgriEd.

publish_to: "none"
version: 1.0.3+0

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.13.0
  file_picker: ^5.0.0
  webview_flutter: ^4.0.0
  responsive_flutter: ^0.0.4
  metadata_fetch: ^0.4.0
  shimmer: ^3.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/flutter_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/dummies/
    - assets/dummies/productivity/
    - assets/images/home/
    - assets/images/resources/
    - assets/images/modules/a/
    - assets/images/modules/b/
    - assets/images/modules/c/
    - assets/images/modules/d/
    - assets/images/reporting/
