name: agried
description: AgriEd.

publish_to: "none"
version: 1.0.2+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  file_picker: ^3.0.0
  webview_flutter: ^2.0.2
  responsive_flutter: ^0.0.4
  metadata_fetch: ^0.3.4
  shimmer: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/dummies/
    - assets/dummies/productivity/
    - assets/images/home/
    - assets/images/resources/
    - assets/images/modules/a/
    - assets/images/modules/b/
    - assets/images/modules/c/
    - assets/images/modules/d/
    - assets/images/reporting/
